-- MySQL Script generated by MySQL Workbench
-- 04/21/17 12:05:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema medhubdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema medhubdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medhubdb` DEFAULT CHARACTER SET utf8 ;
USE `medhubdb` ;

-- -----------------------------------------------------
-- Table `medhubdb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medhubdb`.`company` (
  `id` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Website` VARCHAR(45) NULL DEFAULT NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medhubdb`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medhubdb`.`document` (
  `id` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  `fileName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medhubdb`.`medicalcase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medhubdb`.`medicalcase` (
  `Id` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  `Document_id` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_MedicalCase_Document1_idx` (`Document_id` ASC),
  CONSTRAINT `fk_MedicalCase_Document1`
    FOREIGN KEY (`Document_id`)
    REFERENCES `medhubdb`.`document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medhubdb`.`disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medhubdb`.`disease` (
  `id` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  `MedicalCase_Id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Disease_MedicalCase1_idx` (`MedicalCase_Id` ASC),
  CONSTRAINT `fk_Disease_MedicalCase1`
    FOREIGN KEY (`MedicalCase_Id`)
    REFERENCES `medhubdb`.`medicalcase` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medhubdb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medhubdb`.`location` (
  `id` INT(11) NOT NULL,
  `Country` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(45) NULL DEFAULT NULL,
  `Company_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Location_Company1_idx` (`Company_id` ASC),
  CONSTRAINT `fk_Location_Company1`
    FOREIGN KEY (`Company_id`)
    REFERENCES `medhubdb`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medhubdb`.`userlogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medhubdb`.`userlogin` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `PasswordHash` VARCHAR(256) NULL DEFAULT NULL,
  `PasswordSalt` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medhubdb`.`userprofile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medhubdb`.`userprofile` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `RegistrationDate` DATETIME NULL DEFAULT NULL,
  `Title` VARCHAR(45) NULL DEFAULT NULL,
  `Company_id` INT(11) NULL DEFAULT NULL,
  `MedicalCase_Id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_UserProfile_Company1_idx` (`Company_id` ASC),
  INDEX `fk_UserProfile_MedicalCase1_idx` (`MedicalCase_Id` ASC),
  CONSTRAINT `fk_UserProfile_Company1`
    FOREIGN KEY (`Company_id`)
    REFERENCES `medhubdb`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserProfile_MedicalCase1`
    FOREIGN KEY (`MedicalCase_Id`)
    REFERENCES `medhubdb`.`medicalcase` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medhubdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medhubdb`.`user` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Surname` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `UserProfile_Id` INT(11) NOT NULL DEFAULT '0',
  `UserLogin_Id` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC),
  INDEX `fk_User_UserProfile1_idx` (`UserProfile_Id` ASC),
  INDEX `fk_User_UserLogin1_idx` (`UserLogin_Id` ASC),
  CONSTRAINT `fk_User_UserLogin1`
    FOREIGN KEY (`UserLogin_Id`)
    REFERENCES `medhubdb`.`userlogin` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_User_UserProfile1`
    FOREIGN KEY (`UserProfile_Id`)
    REFERENCES `medhubdb`.`userprofile` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

USE `medhubdb` ;

-- -----------------------------------------------------
-- procedure CreateUser
-- -----------------------------------------------------

DELIMITER $$
USE `medhubdb`$$
CREATE PROCEDURE `CreateUser`(
	IN _Name VARCHAR(45),
    IN _Surname VARCHAR(45),
    IN _Email VARCHAR(45),
    IN _PasswordHash VARCHAR(256),
    IN _PasswordSalt VARCHAR(45),
    IN _UserTitle VARCHAR(45),
    OUT UserID_ INT
)
BEGIN
	DECLARE loginID INT DEFAULT 0;
    DECLARE userProfileID INT DEFAULT 0;
    
	INSERT INTO medhubdb.userlogin(PasswordHash, PasswordSalt)
		VALUES (_PasswordHash, _PasswordSalt);
    
    SET loginID = LAST_INSERT_ID();
    
    SET FOREIGN_KEY_CHECKS = 0;
    
    INSERT INTO medhubdb.userprofile(RegistrationDate, Title)
    VALUES (NOW(), _UserTitle);
	
    SET userProfileID = LAST_INSERT_ID();
    
	INSERT INTO medhubdb.user(Name, Surname, Email, UserLogin_Id, UserProfile_Id)
	VALUES(_Name, _Surname, _Email, loginID, userProfileID);
    
    SET FOREIGN_KEY_CHECKS = 1;
    SET UserID_ = LAST_INSERT_ID();
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure GetPasswordData
-- -----------------------------------------------------

DELIMITER $$
USE `medhubdb`$$
CREATE  PROCEDURE `GetPasswordData`(
	IN _UserEmail VARCHAR(256),
    OUT UserID_ INT,
    OUT PasswordHash_ VARCHAR(256),
    OUT PasswordSalt_ varchar(128)
)
BEGIN
	
    SELECT u.Id, l.PasswordHash, l.PasswordSalt
    INTO UserID_, PasswordHash_, PasswordSalt_
    FROM medhubdb.user u
		INNER JOIN medhubdb.userlogin l
			ON u.UserLogin_Id = l.Id
	WHERE u.Email = _UserEmail;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
